server:
  port: 8080
spring:
  application:
#    应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: Java
      password: 123456
#      redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1704243436@qq.com111
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: wubaoisvmtjneife
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
#  #  邮箱验证码
#  mail:
#    host: smtp.qq.com    #邮箱服务器地址
#    username: 1704243436@qq.com   #邮箱帐号
#    password: wubaoisvmtjneife            #邮箱密码
#    default-encoding: utf-8
#    properties:
#     mail:
#       smtp:
#         auth: true
    #    properties.mail.smtp.ssl.enable: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
#  path: /usr/local/app/images/
  path: D:\桌面\Java文件\com.itheima\瑞吉外卖\1 瑞吉外卖项目\1 瑞吉外卖项目\资料\图片资源\
